"""Membuat tabel ScanEvent

Revision ID: e6a93e8858c4
Revises: 
Create Date: 2025-11-06 22:42:56.364748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a93e8858c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nfc_tag_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status_scan', sa.String(length=50), nullable=False),
    sa.Column('synced_to_main_server', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_event_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_event_timestamp'))

    op.drop_table('scan_event')
    # ### end Alembic commands ###
